source("helper.R")
data <- load.data()
png(file="plot3.png", width=480, height=480)
with(data, plot(PosixDate, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
with(data, lines(PosixDate, Sub_metering_1))
with(data, lines(PosixDate, Sub_metering_2, col="red"))
with(data, lines(PosixDate, Sub_metering_3, col="blue"))
legend("topright", pch=NA, lty=c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
