source("helper.R")
data <- load.data()
png(file="plot1.png", width=480, height=480, bg="transparent")
hist(data$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", main="Global Active Power")
dev.off()